builds:
  - binary: shibayu36
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: zip
  files:
    - README.md
release:
  github:
    owner: shibayu36
    name: shibayu36
  draft: true
