#!/bin/sh

set -e

# Usage:
# $ script/release # Setting github.token in .gitconfig is required
# $ GITHUB_TOKEN=... script/release

latest_tag=$(git describe --abbrev=0 --tags)

goxc
ghr -u shibayu36 -r shibayu36 $latest_tag dist/snapshot/
